### ISSUE TITLE
Error while running : python3 setup.py (DEBUG:root:Could not obtain DS records for rsasha1.example.. pdns output was )

### ISSUE THREAD

**Issue by Rusheelraj** [nils-wisiol/dns-falcon#9]
When I tried to  run the python script I was getting the below error 

![image](https://github.com/nils-wisiol/dns-falcon/assets/30828807/4f3148ac-e34f-4fff-862a-a67782b7b205)

Can you please help me to resolve the same

**Comment by nils-wisiol** [comment]
Did you `docker-compose up -d` before you ran the setup script? If that doesn't help, what is the output of manually running the following?

    docker-compose exec -T auth pdnsutil export-zone-ds rsasha1.example.

**Comment by Rusheelraj** [comment]
Thank you !! 

When I tried the above command i didn't work at first so I tried 

$sudo docker-compose exec -T auth pdnsutil secure-zone /rsasha1.example.

After that, 

$sudo docker-compose exec -T auth pdnsutil export-zone-ds rsasha1.example .

And fate that the python script worked well .
